### ISSUE TITLE
Question 32 

### ISSUE THREAD

**Issue by SadeeshaJayaweera** [Satverse/C-problems-Hacktoberfest2023#33]
Please assign me the question 32 i want to solve it and contribute.

**Comment by krishnapatidar458** [comment]
Note:- Your Pull request should Fulfill all the rules of the Hacktoberfest and open-source contribution.
@SadeeshaJayaweera
#hacktoberfest2023

**Comment by SadeeshaJayaweera** [comment]
please review my pr and merge for the solution i provided. @krishnapatidar458
