### ISSUE TITLE
Questionn 26

### ISSUE THREAD

**Issue by SadeeshaJayaweera** [Satverse/C-problems-Hacktoberfest2023#34]
I want to solve the question 26 and contribute to open source. Please do assign me the question 26 @krishnapatidar458

**Comment by krishnapatidar458** [comment]
Note:- Your Pull request should Fulfill all the rules of the Hacktoberfest and open-source contribution.
@SadeeshaJayaweera 
#hacktoberfest2023

**Comment by SadeeshaJayaweera** [comment]
please review my pr and merge for the solution i provided. @krishnapatidar458
