### ISSUE TITLE
Code to print the sum of first n natural numbers 

### ISSUE THREAD

**Issue by krishnapatidar458** [Satverse/C-problems-Hacktoberfest2023#4]
source file:-https://github.com/krishnapatidar458/C-problems-Hacktoberfest2023/blob/main/solutions/sol003.c

#hacktoberfest2023

**Comment by muruga21** [comment]
hey @krishnapatidar458 can you assign this work to me..?

**Comment by RealCifer** [comment]
hello @krishnapatidar458 hope you are doing good. I want to contribute in this issue

**Comment by krishnapatidar458** [comment]
completed

**Comment by vamus092** [comment]
assign me the task
